
name: 'dbt_project'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +description: "Cleaned raw data with renamed columns and basic casting."
    
    intermediate:
      +description: "Business logic, joins, and complex transformations."
    
    marts: 
      +materialized: table
      +description: "Business-ready dimensional models (Star Schema)."
